module(..., package.seeall)

Strings = {
  chat_hint = "点击开始聊天！",
  league_chat = {
    feedback = "反馈与建议",
    spanish = "西班牙联赛",
    others = "其他比赛",
    italian = "意大利联赛",
    facebook = "在Facebook上给我们点个赞",
    uefa = "欧洲足协赛事",
    german = "德国联赛",
    english = "英格兰联赛",
  },
  friends = "朋友",
  optional = "(Optional)",
  marketing_message_2 = "现在邀请朋友加入到你创建的预测游戏中来吧",
  minigame = {
    friend_help = "已经帮助过你的朋友",
    ask_more_friends = "寻求更多的帮助！",
    winners = "胜者记录",
    current_score = "当前进球数:",
    ask_friends_help = "找朋友来帮忙！",
    failed_to_score = "未能获得任何进球",
    rules = "规则说明",
    helped_to_score = "已经帮助你获得了 %d 个进球",
    title = "进球赢奖品-挑战活动",
    call_to_action = "暂未有人帮你获得过进球",
    no_one_won = "暂无玩家赢得 Samsung Note Edge",
    iPhone6_winner = "Samsung Note Edge 获得者",
    goal_to_win = "还需要 %d 个进球",
    shoot_to_win_won = "你赢了！",
  },
  error = {
    bad_email_format = "错误的邮箱格式",
    blank_password = "密码不能为空",
    no_sms = "手机短信未设置",
    blank_league = "未选择联赛",
    invalid_month = "月份为1至12的数字",
    blank_token = "比赛邀请码不能为空",
    blank_email = "邮箱未填写",
    blank_title = "标题不能为空",
    blank_desc = "描述信息不能为空",
    blank_comp_id = "比赛ID不能为空",
    updating_failed = "配置文件升级失败，请重试",
    login_failed = "登录失败，请重试",
    go_to_store = "前往市场",
    password_long = "密码长度超出限制",
    blank_user_name = "用户名不能为空",
    no_email = "邮箱账号未设置",
    password_not_match = "密码错误",
    password_short = "密码长度过短.",
    match_completed = "已完成本场比赛的预测",
  },
  enter_email = "请输入邮箱地址",
  match_center = {
    played = "已押 %d 共 %d",
    title_discussion = "讨论",
    prediction_made = "已预测",
    title_meetings = "历史交战记录",
    share_title = "",
    less = "合并内容",
    more = "更多内容",
    share_body = "",
    write_discussion = "创建新的话题",
    load_comments = "加载更多评论",
    write_comment = "评论一下",
    title = "比赛中心",
    time_hours = "%d 小时",
    time_days = "%d 天",
    make_prediction = "点击开始预测！",
    just_now = "刚刚发布",
    time_minutes = "%d 分",
  },
  email_signin = "邮箱注册",
  share_type_facebook = "Facebook",
  month = {
    "1月",
    "2月",
    "3月",
    "4月",
    "5月",
    "6月",
    "7月",
    "8月",
    "9月",
    "10月",
    "11月",
    "12月",
  },
  unknown_team = "未知球队",
  leaderboard = {
    gain_per_prediction_title = "场均收益率榜",
    gain_per_prediction_desc = "%d%% 收益 (%d 场预测)",
    high_score_desc = "%d 分 (%d 场预测)",
    high_score_title = "高分榜",
    win_ratio_desc = "%d%% 胜率 (%d 场预测)",
    win_ratio_title = "胜率榜",
  },
  last_name = "姓氏",
  button = {
    ok = "是",
    cancel = "取消",
    yes = "是",
    register = "注册",
    enable = "允许",
    forget_password = "忘记密码？",
    create = "创建！",
    rate_now = "去给Football评分！",
    confirm = "确认！",
    sign_in = "登陆",
    no = "否",
    join = "加入",
    play_now = "开始游戏！",
    share = "分享",
    no_thanks = "否",
    go = "开始！",
  },
  password_confirm = "确认密码",
  spinWheel = {
    ticket_usage = "最新兑换券抽取",
    winners = "胜者记录",
    collect_email_you_won = "你赢得了",
    wheel_title = "超级转转转",
    ticket_balance_2 = "%d 张兑换券",
    win_ticket_left = "剩余",
    spin_daily = "每日一次转盘次数",
    share_description = "分享给朋友获取更多转盘次数！",
    wheel_sub_title = "超级转转转！",
    win_ticket_prize = "幸运兑换券",
    balance_title = "我的积分",
    come_back_in = "下一次游戏时间：",
    no_one_won = "暂无玩家获奖",
    money_balance = "%s 美元亚马逊礼品卡",
    spin_bonus = "奖励旋转次数",
    won = "胜",
    money_payout_success_notification = "请求已处理！你会在接下来的2至4周内通过邮件的方式收到礼品卡！",
    ticket_balance_1 = "%d 张兑换券",
    ticket_you_have = "你拥有",
    leave_message = "明天可以拥有更多转盘次数！",
    money_payout_limit = "提现的最少金额量为25美元",
    collect_email_label_title = "奖品发放",
    claimVirtualPrize = "恭喜！您赢得了一个 %s. 请联系客户服务邮箱！",
    collect_email_towards_wallet = "根据账户余额",
    collect_email_prize = "1 美元",
    collect_email_description = "请提交正确的邮箱地址，不合法的邮箱地址会导致您失去获奖机会。",
  },
  login_success = "登陆成功.\n数据加载中...",
  event = {
    hint_unqualified = "再预测%d场比赛即可拥有获奖资格",
    status_unqualified = "- 未取得获奖资格",
    status_qualified = "- 已拥有获奖资格",
    hint_qualified = "已拥有获奖资格",
    ranking_dropdown_week = "周 %1$d: %3$d月 %2$s日-%5$d月 %4$s日",
    ranking_dropdown_month = "%2$s年 %1$s",
  },
  marketing_message_1 = "恭喜！你刚刚完成了你的第一场预测！",
  facebook_signin = "Facebook账号登陆",
  share_type_title = "通过以下方式分享比赛给你的朋友",
  duration_forever = "无限期",
  marketing_message_3 = "谁会成为预测第一人？",
  serverError = {
    COMPETITION_6 = "日期数据未找到！",
    COUPON_3 = "No predictions on coupon. Cannot place empty coupon.",
    FACEBOOK_2 = "您还未连接到Facebook！",
    DEFAULT = "抱歉请重试！",
    COUPON_1 = "押分数量不合法！",
    LEADERBOARD_2 = "抱歉请重试！",
    LEADERBOARD_1 = "排行榜不合法，请重试！",
    COUNTRY_1 = "请选择其他的国家！",
    COMPETITION_5 = "用户未加入当前比赛！",
    COMPETITION_3 = "邀请码不存在！",
    COMPETITION_2 = "比赛不存在！",
    FACEBOOK_4 = "该Facebook账号已经在使用！",
    WHEEL_3 = "未找到奖励！",
    WHEEL_5 = "请求数量小于最小数额！",
    SIGNIN_2 = "用户名/密码错误！",
    FACEBOOK_3 = "该Facebook账号已经在使用！",
    DISCUSSION_3 = "抱歉请重试！",
    COMPETITION_7 = "不能加入到预览模式的比赛中！",
    GENERAL_2 = "用户ID不合法！",
    SIGNIN_3 = "邮箱不存在",
    WHEEL_6 = "请求数量大于可以用数额！",
    COUPON_4 = "已经参与过一场或一场以上的预测！",
    SIGNIN_1 = "您的邮箱地址无效！",
    VERSION_2 = "请下载新版本的FootballHero获取新特性！",
    COMPETITION_4 = "您已加入当前的比赛！",
    COMPETITION_1 = "您已经创建过相同名字的比赛了",
    FACEBOOK_1 = "软件发生了错误！请重试！",
    WHEEL_1 = "距离上一次使用转盘次数时间小于一天！",
    LEAGUE_1 = "请选择其他的联赛！",
    DISCUSSION_2 = "请重试！",
    COMPETITION_8 = "分享奖励已发放！",
    GENERAL_1 = "抱歉请重试！",
    SIGNIN_4 = "邮箱/密码不能为空",
    COUPON_2 = "Too many predictions on coupon.",
    FACEBOOK_5 = "抱歉请重试！",
    DISCUSSION_1 = "请重试！",
    COUPON_5 = "距离上一次使用三倍押分时间小于12小时！",
    WHEEL_2 = "Price probabilities don't add up.",
    WHEEL_4 = "用户还未使用过转盘次数",
    VERSION_1 = "请在app store中下载最新版本的软件",
  },
  updating_files = "正在升级 %s ...",
  share_type_email = "邮件分享",
  unknown_name = "未知姓名",
  duration_to = "%s 至 %s",
  terms_agree = "登陆即表示您同意FootballHero的相关服务条款",
  last_name_optional = "姓氏 (可选填)",
  community = {
    title_competition = "比赛",
    label_call_to_arm = "您还未加入任何比赛，\n创建比赛并邀请好友加入！",
    enter_comp_code = "输入比赛邀请码",
    title_leaderboard = "榜单",
    desc_create_comp = "在比赛选定的联赛中预测的球赛会自动加入到你的比赛记录中",
    title_create_comp = "的比赛",
  },
  first_name = "名字",
  today = "今日",
  football_hero = "FootballHero",
  push_notification = {
    receive = "你会收到:",
    prediction_summary = "预测汇总",
    match_result = "比赛规则",
    question_competition = "是否开启本场比赛的信息推送",
    question_prediction = "是否开启所有预测的信息推送",
    points_won = "得失分汇总",
    new_participant = "新加入用户通知",
  },
  share_type_SMS = "短信分享",
  info = {
    star_bet = "每过12小时你可以进行一次投入三倍分数的比赛预测",
    new_version = "请下载并升级新版本！",
    join_code_copied = "比赛邀请码已复制",
    predictions_entered = "已完成本场比赛的预测",
    shared_to_fb = "比赛已经分享到Facebook！",
    title = "提示",
  },
  settings = {
    faq = "常见问题",
    sounds = "音效",
    logout = "注销",
    send_feedback = "发送反馈",
    push_notification = "信息推送",
  },
  top_performers = "最佳预测帝",
  chat_room_title = "选择聊天室",
  num_of_points = "%d 分",
  share_title = "加入%s创建的波神比赛",
  quit_cancel = "取消",
  password = "密码",
  choice = {
    leave_comp_desc = "确定要退出当前比赛吗？",
    leave_comp_title = "退出比赛",
  },
  support_title = "用户反馈",
  vs = "VS",
  share_body = "嘿！你能比我预测得更准吗？加入我在波神创建的比分预测大赛吧！邀请码: %s  www.footballheroapp.com/download",
  support_email = "support@footballheroapp.com",
  quit_title = "您确定要退出波神吗?",
  email = "邮箱地址",
  user_name = "用户名",
  history = {
    show_all = "显示所有",
    won_small = "胜",
    predictions_closed = "已预测的比赛",
    lost = "负",
    won_colon = "胜:",
    predictions_open = "正在预测的比赛",
    win_by = "%s 会净胜 %d 球或更多吗?",
    total_goals = "总进球数是否会达到 %d 或更多?",
    won = "胜",
    predictions_all = "所有预测",
    no_open_prediction = "你还没有\n 正在预测的比赛",
    no_open_prediction_others = "没有正在预测的比赛",
    lost_small = "负",
    lost_colon = "负:",
    which_team = "哪支球队会获得胜利?",
    no_closed_prediction = "你还没有\n 已预测的比赛",
    no_closed_prediction_others = "没有已预测的比赛",
  },
  first_name_optional = "名字 (可选填)",
  email_confirm = "确认邮箱地址",
  match_prediction = {
    share = "分享给好友",
    hint_tap = "点击开始预测",
    win = "胜",
    team_to_win = "哪支球队会获得胜利",
    stand_to_win = "押分此项",
    will_total_goals = "总进球数是否会达到 %d 球或更多?",
    balance = "可用分数",
    prediction_summary = "预测汇总",
    facebook = "Facebook",
    stake = "押分\n_webauthserver:*:221:221:Web Auth Se",
    will_win_by = "%s 会净胜 %d 球或更多吗?",
  },
  quit_desc = "再次点击返回退出",
  message_hint = "在此输入消息",
  match_list = {
    date = "%b月 %d日, %A",
    most_popular = "热门比赛",
  },
}


require "DefaultString"

for i = 1 , table.getn( StringDefaultSubTableList ) do
    local subTableTitle = StringDefaultSubTableList[i]
    if Strings[subTableTitle] then
        setmetatable( Strings[subTableTitle], extendsStringDefaultSubTable(subTableTitle) )  
    end
end
setmetatable( Strings, extendsStringDefault() )

CCLuaLog("Load zh string.")