module(..., package.seeall)

MARKET_TYPE_INVALID = 0
MARKET_TYPE_MATCH = 1
MARKET_TYPE_TOTAL_GOAL = 2
MARKET_TYPE_ASIAN_HANDICAP = 3


ODDS_TYPE_ONE_OPTION = 1
ODDS_TYPE_TWO_OPTION = 2
ODDS_TYPE_THREE_OPTION = 3