module(..., package.seeall)

PrizeContent = {
	{	["token"] = "euro2016",
		["1st"] = "Win a Messi Signed Jersey",
		["prizes"] = {
			"Neymar.JR",
			"Thomas Muller",
			"Antoine Griezmann",
			"Xabi Alonso",
			"Oliver Kahn",
			"Santi Cazorla",
			"Ivan Rakitic",
			"Vincent Kompany",
			"Raffael",
			"Uwe Seeler",
			"Thibaut Courtois",
			"Matteo Darmian",
			"Arda Turan",
			"Oribe Peralta",
			"Jasper Cillessen",
			"Nikica Jelavic",
			"Hector Herrera",
			"Giuseppe Rossi",
			"Ezequiel Garay",
			"Andre Wisdom",
			"Steven Naismith",
			"Selcuk Inan",
			"Sebastian Larsson",
		},
	},
	{	["token"] = "americacup2016",
		["1st"] = "Win a Maradona Signed Jersey",
		["prizes"] = {
			"Luis Suarez",
			"James Rodriguez",
			"Xabi Alonso",
			"Jorge Campos",
			"Carlos Valderrama",
			"Raffael",
			"Esteban Cambiasso",
			"Matteo Darmian",
			"Jetro Willems",
			"Darren Bent",
			"Patrick Herrmann",
			"Rui Patricio",
			"Cobi Jones",
			"Gokhan Inler",
			"Gokhan Inler",
			"Ashley Williams",
			"Kim Kallstrom",
			"Thorgan Hazard",
			"Eikrem",
			"Sven Kums",
			"Rui Patricio",
			"Enzo PereZ",
		},
	},
}
