module(..., package.seeall)

Strings = {
	button = {
	    cancel = "Batal",
	    confirm = "OK!",
	    create = "Buat!",
	    enable = "Nyalakan",
	    forget_password = "Lupa kata sandi Anda?",
	    go = "Pergi!",
	    join = "Gabung",
	    no = "Tidak",
	    no_thanks = "Tidak, terima kasih.",
	    ok = "OK",
	    play_now = "Mainkan Sekarang!",
	    register = "Mendaftar",
	    share = "Bagikan",
	    sign_in = "Masuk",
	    yes = "Ya",
	    rate_now = "Nilai sekarang",
	  },
	  chat_hint = "Masukkan pesan",
	  chat_room_title = "Pilih Ruang Chat",
	  choice = {
	    leave_comp_desc = "Keluar dari kompetisi?",
	    leave_comp_no = "Tinggal",
	    leave_comp_title = "Keluar dari kompetisi",
	    leave_comp_yes = "Keluar",
	  },
	  community = {
	    copy = "SALIN",
	    desc_create_comp = "Predikisi yang telah dibuat dalam liga yang terpilih untuk kompetisi akan dimasukkan ke dalam kompetisi secara otomatis.",
	    disclaimer = "*** Sangkalan - Apple bukan sponsor kami dan tidak terlibat dalam hal apapun.",
	    enter_comp_code = "Masukkan Kode",
	    invite_code = "Kode Undangan:",
	    label_call_to_arm = "Anda belum berada di \nkompetisi manapun.\n\n Buat kompetisi yang baru dan\n tantang teman-teman Anda sekarang!",
	    label_fb_share = "Bagikan melalui Facebook",
	    label_give_desc = "Berikan deskripsi",
	    label_give_title = "Berikan judul untuk kompetisi Anda",
	    label_how_long = "Berapa lama akan berlangsung?",
	    label_months  = "bulan",
	    label_ongoing = "tanpa berhenti",
	    label_select_league = "Pilih liga",
	    push = "PEMBERITAHUAN OTOMATIS",
	    quit = "BERHENTI",
	    rules = "PERATURAN",
	    share = "BAGIKAN",
	    title_competition = "Kompetisi",
	    title_create_comp = "Kompetisi",
	    title_description = "Deskripsi",
	    title_details = "Rincian",
	    title_duration = "Durasi",
	    title_eligible = "Liga yang dapat dipilih",
	    title_leaderboard = "Papan Pemain Terbaik",
	    title_joined_comp = "Kompetisi yang diikuti",
	    title_join_comp = "Gabung ke kompetisi",
	    title_rules = "Peraturan",
	    title_top_performers = "Pemain Terbaik",
	  },
	  duration_to = "%s sampai %s",
	  duration_forever = "%s untuk selamanya",
	  email = "Alamat E-mail",
	  email_signin = "Masuk dengan Alamat E-mail",
	  enter_email = "Masukkan alamat e-mail Anda.",
	  error = {
	    bad_email_format = "Format e-mail salah.",
	    blank_comp_id = "IdKompetisi tidak boleh kosong.",
	    blank_desc = "Deskripsi tidak boleh kosong.",
	    blank_email = "Alamat E-mail kosong.",
	    blank_league = "Liga yang terpilih tidak boleh kosong.",
	    blank_password = "Kata Sandi kosong.",
	    blank_title = "Judul tidak boleh kosong.",
	    blank_token = "Kode Kompetisi tidak boleh kosong.",
	    blank_user_name = "Nama pengguna kosong.",
	    go_to_store = "Pergi ke Toko.",
	    invalid_month = "Jumlah bulan bukan angka.",
	    login_failed = "Gagal masuk. Silahkan mecoba kembali.",
	    match_completed = "Anda telah menyelesaikan pertandingan ini.",
	    no_email = "Anda belum mengatur akun E-mail Anda.",
	    no_sms = "Anda belum mengatur SMS Anda.",
	    password_long = "Kata sandi terlalu panjang.",
	    password_not_match = "Kata sandi tidak cocok.",
	    password_short = "Kata sandi terlalu singkat.",
	    title_default = "Oops! Anda mendapatkan pesan error",
	    updating_failed = "Pembaruan konfigurasi gagal. Silahkan mencoba kembali.",
	  },
	  event = {
	    hint_qualified = "Berkualifikasi untuk hadiah",
	    hint_unqualified = "Anda harus membuat prediksi dalam %d pertandingan lagi dalam kompetisi ini agar terkualifikasi untuk hadiah.",
	    predict_now = "Buat Prediksi",
	    prizes = "Hadiah",
	    ranking_monthly = "Bulanan",
	    ranking_overall = "Musim",
	    ranking_dropdown_week = "Minggu %d: %d %s-%d %s",
	    ranking_weekly = "Mingguan",
	    status_qualified = "- berkualifikasi",
	    status_unqualified = "- belum berkualifikasi",
	    total_players = "Jumlah Pemain",
	  },
	  facebook_signin = "Masuk dengan Facebook",
	  first_name = "Nama Depan",
	  first_name_optional = "Nama Depan (Opsional)",
	  football_hero = "FootballHero",
	  friends = "Teman",
	  history = {
	    lost = "Kalah",
	    lost_colon = "Kalah:",
	    lost_small = "kalah",
	    predictions_all = "Semua Prediksi",
	    predictions_closed = "Prediksi Tertutup",
	    predictions_open = "Prediksi Terbuka",
	    show_all = "Tunjukkan Semua",
	    total_goals = "Akankah total gol berjumlah %d atau lebih?",
	    which_team = "Tim manakah yang akan menang?",
	    win_by = "Akankah %s menang dengan selisih %d gol atau lebih?",
	    won = "Menang",
	    won_colon = "Menang:",
	    won_small = "menang",
	    no_open_prediction = "Anda belum memiliki\n pertandingan terbuka.",
	    no_open_prediction_others = "Tidak ada pertandingan terbuka",
	    no_closed_prediction = "Anda belum memiliki\n pertandingan terturup.",
	    no_closed_prediction_others = "Tidak ada pretending tertutup",
	    total_points = "Jumlah Poin: %d",
	    show_all = "Tunjukkan Semua",
	    stake = "Taruhan: %d Poin",
	    win_count = "%d dari %d",
	  },
	  info = {
	    announcement_title = "Pengumuman",
	    competition_not_started = "Kompetisi mulai %s.",
	    join_code_copied = "Kode untuk bergabung telah disalin ke clipboard.",
	    leave_comment1 = "Beritahu kami area yang bisa kami tingkatkan!",
	    leave_comment2 = "Kirim masukan Anda melalui E-mail",
	    like_fh1 = "Apakah Anda menikmati FootballHero sejauh ini?",
	    like_fh2 = "Silahkan ambil beberapa saat untuk menilai aplikasi ini.",
	    new_version = "Silahkan unduh versi terbaru!",
	    odds_not_ready = "Kesempatan akan segera diperbarui.\nSilahkan memeriksa sesaat lagi.",
	    predictions_entered = "Anda telah menyelesaikan pertandingan ini.",
	    shared_to_fb = "Kompetisi telah dibagikan ke Facebook.",
	    shared_to_fb_minigame = "Anda telah membagikan permainan Anda ke Facebook!",
	    star_bet = "Anda bisa menggunakan taruhan berbintang 3 setiap 12 jam",
	    title = "Keterangan",
	  },
	  last_name = "Nama Belakang",
	  last_name_optional = "Nama Belakang (Opsional)",
	  leaderboard = {
	    gain_per_prediction_desc = "%d%% keuntungan (%d prediksi)",
	    gain_per_prediction_title = "Keuntungan per Prediksi",
	    high_score_desc = "%d menang (%d prediksi)",
	    high_score_title = "Skor Tertinggi",
	    me_score = "%d menang",
	    min_prediction = "Paling sedikit %d prediksi",
	    stats_gain_rate = "Keuntungan %",
	    stats_l = "K",
	    stats_last_ten = "10 Terakhir",
	    stats_lose = "Kalah",
	    stats_w = "M",
	    stats_win = "Menang",
	    stats_win_rate = "Menang %",
	    win_ratio_desc = "%d%% menang (%d prediksi)",
	    win_ratio_title = "Perbandingan Kemenangan",
	  },
	  league_chat = {
	    english = "Liga Inggris",
	    facebook = "Sukai kami di Facebook",
	    feedback = "Masukan & Komentar",
	    german = "Liga Jerman",
	    italian = "Liga Itali",
	    others = "Kompetisi Lainnya",
	    spanish = "Liga Spanyol",
	    uefa = "Liga UEFA",
	  },
	  login_success = "Berhasil masuk.\nMemuat data, silahkan tunggu...",
	  marketing_message_1 = "Selamat! Anda telah membuat prediksi pertama",
	  marketing_message_2 = "Sekarang tantang teman-teman Anda di kompetisi kecil Anda!",
	  marketing_message_3 = "Siapa yang akan menjadi pemain terbaik?",
	  match_list = {
	    draw = "Seri",
	    most_popular = "Paling Populer",
	    played = "Dimainkan",
	    special = "Spesial",
	    todays_matches = "Pertandingan Hari Ini",
	    total_fans = "Jumlah Penggemar",
	    upcoming_matches = "Pertandingan Yang Akan Datang",
	  },
	  match_prediction = {
	    balance = "Saldo",
	    facebook = "Facebook",
	    hint_tap = "Tekan untuk membuat prediksi!",
	    prediction_summary = "Ringkasan Prediksi",
	    share = "Bagikan ke teman Anda",
	    stake = "Taruhan",
	    stand_to_win = "Menangkan",
	    team_to_win = "Tim manakah yang akan menang?",
	    will_total_goals = "Akankah total gol berjumlah %d atau lebih?",
	    will_win_by = "Akankah %s menang dengan selisih %d gol atau lebih?",
	    win = "Menang",
	  },
	  message_hint = "Masukkan pesan",
	  month = {
	    "Januari",
	    "Februari",
	    "Maret",
	    "April",
	    "Mei",
	    "Juni",
	    "Juli",
	    "Agustus",
	    "September",
	    "Oktober",
	    "November",
	    "Desember",
	  },
	  minigame = {
	    ask_friends_help = "Minta bantuan teman Anda!",
	    ask_more_friends = "Minta teman-teman lainnya!",
	    call_to_action = "Belum ada yang membantu Anda mencetak gol.",
	    current_score = "Skor Sekarang:",
	    failed_to_score = "Gagal untuk mencetak gol",
	    friend_help = "teman telah membantu Anda",
	    goal_to_win = "%d gol lagi untuk menang",
	    helped_to_score = "telah membantu Anda untuk mencetak %d gol",
	    iPhone6_winner = "Pemenang Samsung Note Edge",
	    no_one_won = "Belum ada yang memenangkan Samsung Note Edge.",
	    rules = "Peraturan",
	    shoot_to_win_won = "Anda menang!",
	    title = "Shoot-to-Win Challenge",
	    winners = "Pemenang yang lalu",
	  },
	  num_of_points = "%d Poin",
	  optional = "(Opsional)",
	  password = "Kata Sandi",
	  password_confirm = "Konfirmasi Kata Sandi",
	  push_notification = {
	    match_result = ". Hasil pertandingan",
	    new_participant = ". Tanda peserta baru",
	    points_won = ". Poin yang telah dimenangkan atau dihilangkan",
	    prediction_summary = ". Ringkasan pertandingan",
	    question_competition = "Apakah Anda ingin menerima pemberitahuan otomatis untuk kompetisi ini?",
	    question_prediction = "Apakah Anda ingin menerima pemberitahuan otomatis untuk semua prediksi Anda?",
	    receive = "Anda akan menerima:",
	  },
	  quit_title = "Apakah Anda ingin keluar?",
	  quit_desc = "Tekan sekali lagi untuk keluar.",
	  quit_cancel = "Tinggal",
	  settings = {
	    faq = "Pertanyaan Umum",
	    general = "Berita Umum",
	    logout = "Keluar",
	    prediction = "Prediksi",
	    push_notification = "Pemberitahuan Otomatis",
	    send_feedback = "Kirim Masukan",
	    sound_effects = "Efek Suara",
	    sound_settings = "Pengaturan Suara",
	    sounds = "Suara",
	    title = "Pengaturan",
	  },
	  share_body = "Dapatkah Anda mengalahkan Saya? Gabung ke dalam kompetisi Saya melalui FootballHero. Kode: %s  www.footballheroapp.com/download",
	  share_title = "Gabung ke kompetisi %s di FootballHero",
	  share_type_email = "Email",
	  share_type_facebook = "Facebook",
	  share_type_SMS = "SMS",
	  share_type_title = "Bagikan kompetisi Anda melalui...",
	  support_email = "support@footballheroapp.com",
	  support_title = "FootballHero - Bantuan",
	  today = "Hari Ini",
	  terms_agree = "Dengan masuk ke aplikasi, Anda menyatakan bahwa Anda telah membaca ketentuan dan setuju dengan ketentuan FootballHero",
	  top_performers = "Pemain Terbaik",
	  unknown_name = "Nama tidak diketahui",
	  unknown_team = "Tim tidak diketahui",
	  updating_files = "Memperbarui %s ...",
	  user_name = "Nama Pengguna",
	  vs = "VS",
}

require "DefaultString"

for i = 1 , table.getn( StringDefaultSubTableList ) do
    local subTableTitle = StringDefaultSubTableList[i]
    if Strings[subTableTitle] then
        setmetatable( Strings[subTableTitle], extendsStringDefaultSubTable(subTableTitle) )  
    end
end
setmetatable( Strings, extendsStringDefault() )

CCLuaLog("Load bahasa string.")